name: chocosales-analyser

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - altair
  - pandas
  - shiny
  - jupyterlab
  - kagglehub
  - plotly
  - pip
  - pip:
      - shinywidgets
      - vega_datasets