name: chocosales-analyser
channels:
- conda-forge
dependencies:
- altair=6.0.0
- kagglehub=1.0.0
- matplotlib=3.10.8
- pandas=3.0.0
- shiny=1.4.0
- plotly=6.5.2
- python=3.14.3
- jupyterlab=4.5.4
- numpy=2.4.2
- shinywidgets=0.7.1
- anywidget=0.9.21
- vega_datasets=0.9.0
- pip
- pip:
  - querychat
  - chatlas
  - python-dotenv