name: chocosales-analyser
channels:
- conda-forge
dependencies:
- python=3.11
- altair=6.0.0
- kagglehub=1.0.0
- matplotlib=3.10.8
- pandas=2.2.3
- shiny=1.4.0
- plotly=6.5.2
- jupyterlab=4.5.4
- numpy
- shinywidgets=0.7.1
- anywidget=0.9.21
- vega_datasets=0.9.0
- pip
- pip:
  - querychat
  - chatlas
  - ibis-framework[duckdb]
  - python-dotenv
  - pytest
  - pytest-playwright